---
title: "Data products"
number-sections: true
---

## Overview {#sec-overview}

SeaBee data products are made publicly available via the [SeaBee GeoNode](https://geonode.seabee.sigma2.no/#/). Products include:

 * **[Datasets](https://geonode.seabee.sigma2.no/catalogue/#/search/?f=dataset)**. Individual data layers, such as raster mosaics, results from machine learning, or vector annotation.
 
 * **[Maps](https://geonode.seabee.sigma2.no/catalogue/#/search/?f=map)**. User-defined maps that combine multiple datasets. For example, a map containing all the data generated by a single SeaBee mission or campaign.
 
 * **[Documents](https://geonode.seabee.sigma2.no/catalogue/#/search/?f=document)**. Relevant non-spatial datasets, such as reports, documentation, etc.
 
 * **[GeoStories](https://geonode.seabee.sigma2.no/catalogue/#/search/?f=geostory)**. Web pages that combine geospatial visualisations with descriptive text and other media to create a story on a particular theme.
 
 * **[Dashboards](https://geonode.seabee.sigma2.no/catalogue/#/search/?f=dashboard)**. Interactive applications allowing users to explore, visualise and analyse SeaBee datasets.

## Using SeaBee data in other applications {#sec-other-apps}

All datasets hosted on SeaBee's GeoNode are exposed as Web Mapping Services (WMSs), which users can add to their own maps or applications (e.g. in ArcGIS or QGIS). To do this, add a new WMS server to your application with the following URL

 <https://geonode.seabee.sigma2.no/geoserver/geonode/wms?version=1.1.1>
 
This will allow you to load a list of available SeaBee data layers and add them to your map. The WMSs can also be used to build third-party applications that incorporate SeaBee data products.

## Registered users {#sec-registered-users}

SeaBee data is available to everyone, but registered users can download data products for their own use. They can also create, style and share their own maps by combining multiple SeaBee datasets. Click the `Register` button at the top-right of the [GeoNode home page](https://geonode.seabee.sigma2.no/#/) to create an account.

## Data licensing {#sec-licensing}

The SeaBee platform supports licensing on a per-dataset basis. By default, SeaBee datasets are published under a **CC-BY-4.0** licence, which permits sharing and adapting the data (including for commercial purposes), as long as SeaBee is credited as the data source. See [here](https://creativecommons.org/licenses/by/4.0/) for details.

::: {.callout-important}
Some SeaBee datasets **do not** use the `CC-BY-4.0` licence. Please check the `Licence` and `Licence link` attributes in the dataset abstract to find the correct licence.
:::