---
title: "How to"
number-sections: true
---

I want to...

## Create a user account {#sec-create-account}

You need to create a Feide account and then request access to the resources you will need. See the [Login](./login.qmd) page for details.

## Upload or download files {#sec-file-transfer}

The best option will depend on your level of technical expertise and the volume of data you wish to transfer. Non-technical users with smaller data volumes should consider the [MinIO web interface](https://minio.seabee.sigma2.no/). For larger volumes of data (e.g. raw imagery for whole missions), dedicated software such as **Rclone** and **RcloneBrowser** are preferable. See [Uploading and downloading files](./storage.qmd#uploading-and-downloading-files) for details.

## Mosaic geotagged raw images to georeferenced mosaics {#sec-orthorectification}

If you are a drone pilot wishing to upload mission data for automatic processing, see the data preparation guide [here](./data-upload.qmd). The basic procedure involves uploading your raw images in a single folder, together with a plain text file called `config.seabee.yaml` containing simple metadata. If you wish to have more control over the exact processing workflow, you can use NodeODM/Open Drone Map via PyODM from any of the SeaBee JupyterHubs. See the [Orthorectification](./orthorectification.qmd) page for details. 

## Create training data for machine learning (annotation) {#sec-annotation}

The recommended workflow for **image segmentation** tasks is to use ArcGIS Pro and the Image Analyst extension - see the [Annotation](./annotation.qmd) page for details.

## Explore and download SeaBee datasets {#sec-explore-data}

Orthomosaics from aerial drones and data products from machine learning are available via the [SeaBee GeoNode](https://geonode.seabee.sigma2.no/). See the [Data products](./data-products.qmd) page for details.

## Create shareable maps combining multiple datasets {#sec-share-maps}

You first need to **register** as a user of the GeoNode (click the button near the top-right of the [map page](https://geonode.seabee.sigma2.no/catalogue/#/search/?f=dataset)). Once signed in, you can use the `Add resource` button to create a new `Map`, where you can choose which layers to add and adjust their styling etc. Maps you create are linked to your username and will become visible on the [Maps](https://geonode.seabee.sigma2.no/catalogue/#/search/?f=map) page. All user-generated maps are public and can be shared online.