---
title: "Standardised imagery"
number-sections: true
---

Orthorectified images often need standardising and stacking to create "composite" images before being used in the rest of the SeaBee workflow. This page defines some standards and recommendations for SeaBee datasets.

:::{.callout-tip}
The easiest way to ensure your data matches the formats and standards expected is to upload your raw images to the SeaBee platform and perform all subsequent processing (orthomosaicing etc.) there, instead of on your local machine. The SeaBee data pipeline will then automatically take care of any standardisation required.
:::

## Band order {#sec-band-order}

For multiband images, **bands should be stacked in order of descending wavelength** (i.e. band 1 corresponds to the longest wavelength and band $n$ to the shortest):

 * For RGB datasets, `R, G, B = bands 1, 2, 3`
 
 * For typical multispectral data, `NIR, RE, R, G, B = bands 1, 2, 3, 4, 5` (where `NIR` corresponds to "near infrared" and `RE` is "red edge")

Note that GeoTiffs support band-level metadata via [set_band_description](https://rasterio.readthedocs.io/en/stable/api/rasterio.io.html#rasterio.io.BufferedDatasetWriter.set_band_description). It is strongly recommended to use this to explicitly set the band name or wavelength interval for each band. This makes it easy to check whether a file matches the recommended format.

:::{.callout-tip}
By default, most GIS software will display bands 1, 2 and 3 as R, G and B, respectively. However, it is usually easy to change these settings and assign colours to whichever bands you wish:

 * In ArcGIS Desktop, use the [Symbology](https://resources.arcgis.com/en/help/main/10.2/index.html#/Drawing_a_multiband_raster_dataset_as_an_RGB_composite/009t00000073000000/) tab
 * In ArcGIS Pro, use the [Raster Layer](https://desktop.arcgis.com/en/arcmap/latest/manage-data/raster-and-images/setting-the-default-bands-to-display-multiband-rasters.htm) tab
 * For QGIS, see the [Raster Properties](https://docs.qgis.org/3.22/en/docs/user_manual/working_with_raster/raster_properties.html?highlight=multiband#multiband-color) dialog
:::

## Handling missing data {#sec-nodata}

There are three common approaches for representing "no data" in raster imagery: setting a `nodata` value, using an "alpha channel" and using a mask. Using an alpha channel avoids reserving a specific pixel value for no data, making it possible to use the full range of values for the data type. However, alpha masks are not supported by some software and image compression algorithms. For the time being, it is recommended to **discard any alpha channels and explicitly set a `nodata` value** (but see the issue [here](https://github.com/SeaBee-no/documentation/issues/30) for the latest advice).

:::{.callout-note}
RGB mosaics produced by SeaBee cameras are usually RGBA (i.e. they include an alpha band); multispectral mosaics typically do not.
:::

## Bit depth {#sec-bit-depth}

8-bits per band is considered sufficient for most machine learning applications on the SeaBee platform. Raw data with higher bit depths should be stored on MinIO, but for machine learning it is recommended to **convert each band to 8-bit integer type** before stacking. Be sure to scale - rather than truncate - the values when converting.

SeaBee workflows are not limited to 8-bits per band. Please let us know if you believe your workflow will benefit from using higher bit depths.

:::{.callout-note}
SeaBee RGB mosaics are typically 8-bit by default; the multispectral cameras usually produce 32-bit bands.
:::