---
title: "Storage"
number-sections: true
---

## Overview

 * Describe MinIO instance, how to login, basic bucket/folder structure etc.
 * S3-compatible storage endpoint at <https://storage.seabee.sigma2.no>
 * Web interface at <https://minio.seabee.sigma2.no/login>

## Backups

 * Describe backup schedule

## Uploading and downloading files

 * Describe options for uploading and download, including detailed configuration steps

### MinIO web interface

 * Overview of the web UI
 * How to manually browse, upload and download files
 * What should go where?
 * How should files be structured?

### SeaBee data upload portal

 * Describe Deb's data upload portal
 * Best option for standard/less advanced users?

### Python API

 * Possible to up/download using Python?
 * Can this be done from an external machine, or only from the SeaBee JupyterHub?
 * Based on Kim's example [here](https://nbviewer.org/github/SeaBee-no/snippets/blob/main/storage.ipynb)

### Rclone

[Rclone](https://rclone.org/) provides a convenient way of synchronising local files to cloud storage. **It is probably the best option for experienced/advanced users to add large volumes of imagery to Sigma2**.

 * Describe the configuration required to get Rclone working with MinIO on Sigma2
